In [17]:
def print_dataset(ds):
    for inputs, targets in ds:
        print("---Batch---")
        print("Feature:", inputs.numpy())
        print("Label:", targets.numpy())
        print("")

In [204]:
from tensorflow.keras.preprocessing import timeseries_dataset_from_array
import numpy as np

x = np.array([[1,1,1,1,1,1,1],
              [2,2,2,2,2,2,2],
              [3,3,3,3,3,3,3],
              [4,4,4,4,4,4,4],
              [5,5,5,5,5,5,5]   
              ])
y = np.array([[-1],
              [-2],
              [-3],
              [-4],
              [-5]   
              ])
xx = np.concatenate((x, x+100), axis=0)#.reshape(2,5,6)  
yy = np.concatenate((y, y-100), axis=0)
    
sequence_length=2
stride=1
rate=1
batch_size = 1
input_dataset = timeseries_dataset_from_array(xx,
                                              yy,
                                              sequence_length,
                                              sequence_stride=stride,
                                              batch_size=batch_size,
                                              sampling_rate=rate)

#x_test = np.concatenate([x for x in input_dataset], axis=0)

In [197]:
print_dataset(input_dataset)

---Batch---
Feature: [[[1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2]]]
Label: [[-1]]

---Batch---
Feature: [[[2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3]]]
Label: [[-2]]

---Batch---
Feature: [[[3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4]]]
Label: [[-3]]

---Batch---
Feature: [[[4 4 4 4 4 4 4]
  [5 5 5 5 5 5 5]]]
Label: [[-4]]

---Batch---
Feature: [[[  5   5   5   5   5   5   5]
  [101 101 101 101 101 101 101]]]
Label: [[-5]]

---Batch---
Feature: [[[101 101 101 101 101 101 101]
  [102 102 102 102 102 102 102]]]
Label: [[-101]]

---Batch---
Feature: [[[102 102 102 102 102 102 102]
  [103 103 103 103 103 103 103]]]
Label: [[-102]]

---Batch---
Feature: [[[103 103 103 103 103 103 103]
  [104 104 104 104 104 104 104]]]
Label: [[-103]]

---Batch---
Feature: [[[104 104 104 104 104 104 104]
  [105 105 105 105 105 105 105]]]
Label: [[-104]]



In [198]:
[x for x in input_dataset]

[(<tf.Tensor: shape=(1, 2, 7), dtype=int32, numpy=
  array([[[1, 1, 1, 1, 1, 1, 1],
          [2, 2, 2, 2, 2, 2, 2]]])>,
  <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[-1]])>),
 (<tf.Tensor: shape=(1, 2, 7), dtype=int32, numpy=
  array([[[2, 2, 2, 2, 2, 2, 2],
          [3, 3, 3, 3, 3, 3, 3]]])>,
  <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[-2]])>),
 (<tf.Tensor: shape=(1, 2, 7), dtype=int32, numpy=
  array([[[3, 3, 3, 3, 3, 3, 3],
          [4, 4, 4, 4, 4, 4, 4]]])>,
  <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[-3]])>),
 (<tf.Tensor: shape=(1, 2, 7), dtype=int32, numpy=
  array([[[4, 4, 4, 4, 4, 4, 4],
          [5, 5, 5, 5, 5, 5, 5]]])>,
  <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[-4]])>),
 (<tf.Tensor: shape=(1, 2, 7), dtype=int32, numpy=
  array([[[  5,   5,   5,   5,   5,   5,   5],
          [101, 101, 101, 101, 101, 101, 101]]])>,
  <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[-5]])>),
 (<tf.Tensor: shape=(1, 2, 7), dtype=int32, num

In [206]:
xxx = xx.reshape(2,5,7)  
yyy = yy.reshape(2,5,1)

# create two tensorflow datasets
input_dataset0 = timeseries_dataset_from_array(xxx[0,:,:],
                                               yyy[0,:,:],
                                               sequence_length,
                                               sequence_stride=stride,
                                               batch_size=batch_size,
                                               sampling_rate=rate)
input_dataset1 = timeseries_dataset_from_array(xxx[1,:,:],
                                               yyy[1,:,:],
                                               sequence_length,
                                               sequence_stride=stride,
                                               batch_size=batch_size,
                                               sampling_rate=rate)
# concatenate the two tensorflow datasets
input_dataset = input_dataset0.concatenate(input_dataset1)

x_test = np.concatenate([x for x, y in input_dataset], axis=0)


In [208]:
x_test

array([[[  1,   1,   1,   1,   1,   1,   1],
        [  2,   2,   2,   2,   2,   2,   2]],

       [[  2,   2,   2,   2,   2,   2,   2],
        [  3,   3,   3,   3,   3,   3,   3]],

       [[  3,   3,   3,   3,   3,   3,   3],
        [  4,   4,   4,   4,   4,   4,   4]],

       [[  4,   4,   4,   4,   4,   4,   4],
        [  5,   5,   5,   5,   5,   5,   5]],

       [[101, 101, 101, 101, 101, 101, 101],
        [102, 102, 102, 102, 102, 102, 102]],

       [[102, 102, 102, 102, 102, 102, 102],
        [103, 103, 103, 103, 103, 103, 103]],

       [[103, 103, 103, 103, 103, 103, 103],
        [104, 104, 104, 104, 104, 104, 104]],

       [[104, 104, 104, 104, 104, 104, 104],
        [105, 105, 105, 105, 105, 105, 105]]])

In [207]:
x_test.shape

(8, 2, 7)

In [200]:
print_dataset(input_dataset)

---Batch---
Feature: [[[1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2]]]
Label: [[-1]]

---Batch---
Feature: [[[2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3]]]
Label: [[-2]]

---Batch---
Feature: [[[3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4]]]
Label: [[-3]]

---Batch---
Feature: [[[4 4 4 4 4 4 4]
  [5 5 5 5 5 5 5]]]
Label: [[-4]]

---Batch---
Feature: [[[101 101 101 101 101 101 101]
  [102 102 102 102 102 102 102]]]
Label: [[-101]]

---Batch---
Feature: [[[102 102 102 102 102 102 102]
  [103 103 103 103 103 103 103]]]
Label: [[-102]]

---Batch---
Feature: [[[103 103 103 103 103 103 103]
  [104 104 104 104 104 104 104]]]
Label: [[-103]]

---Batch---
Feature: [[[104 104 104 104 104 104 104]
  [105 105 105 105 105 105 105]]]
Label: [[-104]]



In [209]:
[x.numpy() for x in input_dataset]

AttributeError: 'tuple' object has no attribute 'numpy'